# Generated by Django 4.2.6 on 2023-11-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('semail', models.CharField(max_length=250)),
                ('ssub', models.CharField(max_length=100)),
                ('sadd', models.CharField(max_length=300)),
            ],
        ),
    ]
