# Generated by Django 4.2.6 on 2023-11-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='sadd',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='semail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ssub',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('pprice', models.IntegerField()),
                ('pdiscount', models.IntegerField()),
                ('pimg', models.ImageField(upload_to='pimg/')),
                ('pdisc', models.TextField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.catagory')),
            ],
        ),
    ]
