# Generated by Django 4.2.6 on 2023-12-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_catagory_alter_shop_sadd_alter_shop_semail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='sadd',
            new_name='smessage',
        ),
    ]
