# Generated by Django 4.2.6 on 2023-12-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_rename_sadd_shop_smessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shop',
            new_name='Contact',
        ),
    ]
