# Generated by Django 4.2.6 on 2023-12-07 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0004_rename_shop_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
